### ISSUE TITLE
Make *_seq.h5 file from orf fasta/gff, for shiny integration from new annotations

### ISSUE THREAD

**Issue by ewallace** [shahpr/RiboViz#28]
To apply shiny to new (non-yeast) datasets, we need to compute new *codonseq*/*nseq* inputs from the *orf_fasta* and *orf_gff_file* inputs and store them in a named *\*.h5* file. This name should be listed in the *config.yaml* as an input file. 

Premal/Oana, if you can start a branch with the code you used to make *yeast_seq.h5* and a description of its structure, I can take a look.

Edward

**Comment by shahpr** [comment]
Script for generating `codon` and `nt` seq inputs from `*.h5` files is added to `script_for_transcript_annotation.Rmd` file.
