### ISSUE TITLE
Multi-core adapter trimming

### ISSUE THREAD

**Issue by ewallace** [shahpr/RiboViz#30]
Adapter trimming is the slowest part of RiboViz because it's not parallelized.

We should change that by either using cutadapt multi-core:
https://cutadapt.readthedocs.io/en/stable/guide.html#multicore
-j nprocesses

or moving to flexbar or another multi-core trimmer.

**Comment by shahpr** [comment]
Added multicore option for cutadapt by default. The code uses the `nprocesses` argument from the YAML file to specify the number of cores for cutadapt.

**Comment by ewallace** [comment]
This is great, unless you don't have a python 3 installation, in which case cutadapt fails with error:
ERROR: Running in parallel is not supported on Python 2

I'm not sure what to do about it, but wanted to flag.
