### ISSUE TITLE
3nt periodicity appears to be broken

### ISSUE THREAD

**Issue by ewallace** [shahpr/RiboViz#32]
In the latest version, 3' periodicity plots aren't looking right, e.g. when I run the vignette:

[WTnone_3nt_periodicity.pdf](https://github.com/shahpr/RiboViz/files/1896192/WTnone_3nt_periodicity.pdf)

I'm not sure where the problem is, but the bam/bedgraph files look fine, so something in bam_to_h5.R or a change in dependencies?

**Comment by ewallace** [comment]
Update, June 2018: 3nt periodicity works on S. cerevisiae data when I use the most recent CDS + fixed 250nt buffer files (yeast_CDS_w_250utrs.fa/.gff3).

We should test with
- alternative fixed-length buffers (not 250nt)
- non-fixed buffers as specified from annotated UTR lengths.

**Comment by shahpr** [comment]
- Added functionality to specify a variable buffer size based on 5' and 3' UTR lengths.
- The lengths are obtained from the GFF file generated using [script_for_transcript_annotation](https://github.com/shahpr/RiboViz/blob/master/scripts/script_for_transcript_annotation.Rmd)
