### ISSUE TITLE
UMI resolution *and* trimming with fastp?

### ISSUE THREAD

**Issue by ewallace** [shahpr/RiboViz#45]
I'm wondering if fastp will solve a bunch of RiboViz problems:
"In this paper, we present fastp, an ultra-fast tool to perform quality control, read filtering and base correction for FASTQ data. It includes most features of FASTQC + Cutadapt + Trimmomatic + AfterQC while running 2–5 times faster than any of them alone. In addition to the functions available in these tools, fastp offers supplementary features such as unique molecular identifier (UMI) preprocessing, per-read polyG tail trimming and output splitting. fastp also provides quality control reports for pre- and post-filtered data within a single HTML page, which allows for direct comparison of quality statistics altered by preprocessing."
https://academic.oup.com/bioinformatics/article/34/17/i884/5093234

Requesting we test fastp for faster and more streamlined read preprocessing.

**Comment by shahpr** [comment]
We tried integrating fastp for demultiplexing using UMIs for our sequencing runs. However, the UMI pre-processing is fastp is very limited. It allows for UMIs in only one at the head of the reads. Our UMIs are sandwiched between the read and the 3' Illumina adapters.

**Comment by ewallace** [comment]
Makes sense. I'm sure we can find a solution to this to incorporate into the pipeline, even if it means writing our own UMI remover.

Can you provide a description of the read features including UMI and adapters? Then we can produce sample input and output to test if it works. 

Did fastp work to replace cutadapt just for adapter trimming and QC?

**Comment by ewallace** [comment]
Migrated to https://github.com/riboviz/RiboViz/issues/79

UMI issue fixed in https://github.com/riboviz/RiboViz/issues/58
